---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: csharp-rest-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: csharp-rest-service
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: csharp-rest-service
    tanzu.app.live.view.application.actuator.port: "9090"
spec:
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: "true"
    - name: BP_ENABLE_CA_CERTIFICATES
      value: "true" # Enable CA Certificates Buildpack
    - name: SSL_CERT_DIR
      value: "/etc/ssl/certs" # Default trust store path
    volumes:
      - name: custom-certs-volume
        secret:
          secretName: custom-certs # Reference the secret
    volumeMounts:
      - name: custom-cert-volume
        mountPath: /etc/ssl/certs # Mount certificates into the trust store
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"

  source:
    git:
      url: https://github.com/rabadiw/csharp-service-testing.git
      ref:
        branch: main

  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: customer-database
